# Dockerfile.nginx
FROM nginx:1.25-alpine

# Copy file cấu hình
COPY nginx.conf /etc/nginx/nginx.conf

# Copy thư mục chứng chỉ (Lưu ý: folder certs phải nằm cùng chỗ với file này khi build)
COPY certs /etc/nginx/certs