services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: healthsync-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1434:1433"
    networks:
      - healthsync-network

  minio:
    image: minio/minio
    container_name: healthsync-minio
    environment:
      # Cấu hình User/Pass (Chuẩn mới dùng ROOT thay vì ACCESS_KEY)
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # Cấu hình tên miền riêng
      # Đây là địa chỉ dùng để truy cập file/ảnh
      - MINIO_SERVER_URL=http://files.healthsync.local:9000
      # Đây là địa chỉ trang quản trị (Console)
      - MINIO_BROWSER_REDIRECT_URL=http://console.healthsync.local:9001
    volumes:
      # Cách 1: Dùng volume nội bộ của Docker (như code cũ của bạn)
      - minio_data:/data 
      
      # Cách 2: Map ra ổ cứng thật (Khuyên dùng để giữ dữ liệu cũ bạn đã copy)
      # - D:/MinioData:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - healthsync-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    depends_on:
      - db
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=HealthSyncDb;User Id=sa;Password=YourStrong!Passw0rd123;TrustServerCertificate=True;
      # API giao tiếp nội bộ với MinIO thì vẫn dùng tên container "minio" cho nhanh
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=${MINIO_ACCESS_KEY}
      - MinIO__SecretKey=${MINIO_SECRET_KEY}
      - MinIO__BucketName=${MINIO_BUCKET_NAME}
      - MinIO__UseSSL=false
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - healthsync-network

  nginx:
    image: nginx:1.25-alpine
    container_name: healthsync-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - healthsync-network

  jenkins:
    image: jenkins/jenkins:lts-alpine
    container_name: healthsync-jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Jenkinsfile:/var/jenkins_home/Jenkinsfile:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - healthsync-network

volumes:
  sqlserver_data:
  minio_data:
  jenkins_data:

networks:
  healthsync-network:
    driver: bridge