# Use the official .NET 8.0 SDK image to run migrations
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
WORKDIR /src

# Copy the project files and restore dependencies
COPY ["HealthSync.WebApi/HealthSync.WebApi.csproj", "HealthSync.WebApi/"]
COPY ["HealthSync.Application/HealthSync.Application.csproj", "HealthSync.Application/"]
COPY ["HealthSync.Domain/HealthSync.Domain.csproj", "HealthSync.Domain/"]
COPY ["HealthSync.Infrastructure/HealthSync.Infrastructure.csproj", "HealthSync.Infrastructure/"]
RUN dotnet restore "HealthSync.WebApi/HealthSync.WebApi.csproj"

# Copy the entire source code
COPY . .

# Set the working directory to the Infrastructure project for EF tools
WORKDIR "/src/HealthSync.Infrastructure"

# Run the migration command
CMD ["dotnet", "ef", "database", "update", "--startup-project", "../HealthSync.WebApi"]